export type PlateSystem = "ivory-coupe" | "charcoal-kadhai" | "bread-basket";

export type VisualCompliance = "pass" | "temporary" | "reject";

export type PlatingAudit = {
  targetPlateSystem: PlateSystem;
  actualVisiblePlate: string;
  actualBackground: string;
  actualCameraAngle: string;
  actualLightingStyle: string;
  visualCompliance: VisualCompliance;
  complianceReason: string;
  menuEligible: boolean;
  replacementRecommendation: string;
};

const reviewed = (
  targetPlateSystem: PlateSystem,
  actualVisiblePlate: string,
  actualBackground: string,
  actualCameraAngle: string,
  visualCompliance: VisualCompliance,
  complianceReason: string,
  replacementRecommendation: string,
  actualLightingStyle = "soft diffused studio light",
): PlatingAudit => ({
  targetPlateSystem,
  actualVisiblePlate,
  actualBackground,
  actualCameraAngle,
  actualLightingStyle,
  visualCompliance,
  complianceReason,
  menuEligible: visualCompliance === "pass",
  replacementRecommendation,
});

const ivoryReshoot =
  "Reshoot on a matte ivory coupe plate over warm limestone at a restrained 35–45-degree or overhead angle.";
const kadhaiReshoot =
  "Reshoot in the approved matte charcoal kadhai over warm limestone or cool pale stone.";
const basketReshoot =
  "Reshoot in the approved natural basket with a consistent black-and-cream liner over warm limestone.";

export const platingAuditByImageId: Record<string, PlatingAudit> = {
  "food-bharwan-paneer-tikka": reviewed(
    "ivory-coupe",
    "black plate on a large gold charger",
    "warm limestone",
    "restrained overhead",
    "reject",
    "The visible gold charger and black center plate are not an ivory coupe plate.",
    ivoryReshoot,
  ),
  "food-bhutte-ke-kebab": reviewed(
    "ivory-coupe",
    "pale stone round coupe plate",
    "soft greige",
    "restrained overhead",
    "pass",
    "The visible pale round plate, neutral background, scale, and crop match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-buratta-bomb": reviewed(
    "ivory-coupe",
    "white round coupe plate",
    "soft greige",
    "35–45-degree",
    "pass",
    "The white coupe plate and neutral studio presentation match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-burrata-chaat": reviewed(
    "ivory-coupe",
    "white round coupe plate",
    "cool pale stone",
    "restrained overhead",
    "pass",
    "The white round plate and controlled pale-stone background match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-chapli-smash-burger": reviewed(
    "ivory-coupe",
    "black slate platter over banana leaf",
    "soft greige",
    "35–45-degree",
    "reject",
    "Black slate and direct banana-leaf presentation are prohibited for the ivory-coupe system.",
    ivoryReshoot,
  ),
  "food-cheese-naan": reviewed(
    "bread-basket",
    "natural basket with black-and-cream liner",
    "warm limestone",
    "restrained overhead",
    "pass",
    "The basket, liner, background, and bread scale match the bread-basket system.",
    "Retain the reviewed source and crop.",
  ),
  "food-chicken-boneless-biryani": reviewed(
    "charcoal-kadhai",
    "light gray shallow bowl with white ramekins",
    "cool pale stone and linen",
    "35–45-degree",
    "temporary",
    "The vessel is not matte charcoal and the photograph is not mapped to an exact approved menu item.",
    kadhaiReshoot,
  ),
  "food-chur-chur-naan": reviewed(
    "bread-basket",
    "bread directly on checkered liner without basket",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The source lacks the required basket and exposes an orange wood background.",
    basketReshoot,
  ),
  "food-coconut-carrot-soup": reviewed(
    "charcoal-kadhai",
    "coconut shell beside a banana leaf",
    "white studio surface",
    "35–45-degree",
    "reject",
    "A coconut shell is not the approved charcoal kadhai and the presentation introduces a conflicting leaf prop.",
    kadhaiReshoot,
  ),
  "food-unidentified-dessert": reviewed(
    "ivory-coupe",
    "large blue coupe bowl",
    "white studio surface",
    "35–45-degree",
    "reject",
    "The blue vessel does not match ivory-coupe and the dessert identity is unconfirmed.",
    ivoryReshoot,
  ),
  "food-bhatti-da-kukarh": reviewed(
    "ivory-coupe",
    "white round coupe plate",
    "soft greige linen",
    "35–45-degree",
    "pass",
    "The visible white coupe plate and neutral background match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-classic-chicken-tikka": reviewed(
    "ivory-coupe",
    "white round coupe plate",
    "warm limestone",
    "35–45-degree",
    "pass",
    "The visible white round plate and neutral background match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-lamb-seekh-kebab": reviewed(
    "ivory-coupe",
    "clear glass plate over white surface",
    "white studio surface",
    "restrained overhead",
    "temporary",
    "The presentation is neutral but the clear glass plate is not the approved matte ivory coupe.",
    ivoryReshoot,
  ),
  "food-tandoori-full": reviewed(
    "ivory-coupe",
    "black tabletop grill",
    "soft greige",
    "35–45-degree",
    "reject",
    "A tabletop grill is explicitly prohibited for the ivory-coupe system.",
    ivoryReshoot,
  ),
  "food-tandoori-masaledar-lamb-chops": reviewed(
    "ivory-coupe",
    "pale green ceramic plate over banana leaf",
    "soft greige",
    "35–45-degree",
    "reject",
    "The green plate and banana-leaf presentation do not match the ivory-coupe system.",
    ivoryReshoot,
  ),
  "food-tandoori-salmon": reviewed(
    "ivory-coupe",
    "gray-green ceramic plate",
    "soft greige",
    "35–45-degree",
    "temporary",
    "The controlled presentation is close, but the visibly gray-green plate is not matte ivory.",
    ivoryReshoot,
  ),
  "food-garlic-naan": reviewed(
    "bread-basket",
    "natural basket with black-and-cream liner",
    "warm limestone",
    "restrained overhead",
    "pass",
    "The visible basket and liner match the bread-basket system.",
    "Retain the reviewed source and crop.",
  ),
  "food-hara-bhara-kebab": reviewed(
    "ivory-coupe",
    "food directly on a full banana leaf",
    "soft greige",
    "35–45-degree",
    "reject",
    "Food presented directly on a full banana leaf without a plate is explicitly prohibited.",
    ivoryReshoot,
  ),
  "food-hyderabadi-chicken-dum-biryani": reviewed(
    "charcoal-kadhai",
    "terracotta handi with separate ramekins",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The terracotta vessel and exposed orange wood do not match the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-jhol-momo-non-veg": reviewed(
    "ivory-coupe",
    "dark blue coupe bowl",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The blue bowl and exposed wood background do not match the ivory-coupe system.",
    ivoryReshoot,
  ),
  "food-lachcha-paratha": reviewed(
    "bread-basket",
    "natural basket with black-and-cream liner",
    "warm limestone",
    "restrained overhead",
    "pass",
    "The basket, liner, crop, and bread scale match the bread-basket system.",
    "Retain the reviewed source and crop.",
  ),
  "venue-main-outdoor": reviewed(
    "ivory-coupe",
    "not applicable; restaurant exterior",
    "night exterior",
    "eye level",
    "reject",
    "This venue photograph is not food photography and is never eligible for menu placement.",
    "Keep as venue/gallery media only.",
    "available exterior light",
  ),
  "food-malai-tandoori-broccoli": reviewed(
    "ivory-coupe",
    "gray metal plate over banana leaf",
    "soft greige",
    "35–45-degree",
    "reject",
    "The gray vessel and banana-leaf presentation do not match the ivory-coupe system.",
    ivoryReshoot,
  ),
  "food-masala-roti": reviewed(
    "bread-basket",
    "natural basket with black-and-cream liner",
    "exposed orange wood",
    "restrained overhead",
    "temporary",
    "The serving basket is correct, but the exposed orange wood background is not approved for public menu photography.",
    "Reshoot the same basket and liner over warm limestone.",
  ),
  "food-murgh-badam-shorba": reviewed(
    "charcoal-kadhai",
    "white round bowl",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The white bowl and exposed orange wood conflict with the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-fish-moilee": reviewed(
    "charcoal-kadhai",
    "dark blue wide-rim bowl",
    "charcoal surface",
    "35–45-degree",
    "reject",
    "The blue fine-dining bowl is explicitly excluded from the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-prawn-mango-curry": reviewed(
    "charcoal-kadhai",
    "pale green plate with separate white bowl",
    "cool pale stone",
    "35–45-degree",
    "reject",
    "The pale green plate and separate white bowl do not match the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-butter-chicken": reviewed(
    "charcoal-kadhai",
    "pale green ceramic bowl",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The green bowl and exposed wood background are explicitly noncompliant.",
    kadhaiReshoot,
  ),
  "food-chicken-korma": reviewed(
    "charcoal-kadhai",
    "pale green ceramic bowl",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The green bowl and exposed wood background are explicitly noncompliant.",
    kadhaiReshoot,
  ),
  "food-chicken-tikka-masala": reviewed(
    "charcoal-kadhai",
    "small white bowl",
    "white studio surface",
    "restrained overhead",
    "reject",
    "A white fine-dining bowl is explicitly excluded from the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-chicken-vindaloo": reviewed(
    "charcoal-kadhai",
    "white ceramic bowl",
    "white studio surface",
    "35–45-degree",
    "reject",
    "A white bowl is explicitly excluded from the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-coriander-prawns": reviewed(
    "charcoal-kadhai",
    "antique brass kadhai",
    "cool pale stone",
    "restrained overhead",
    "temporary",
    "The Indian vessel and background are controlled, but the vessel is bright brass rather than matte charcoal or dark pewter.",
    kadhaiReshoot,
  ),
  "food-kadai-chicken": reviewed(
    "charcoal-kadhai",
    "brass kadhai on a wooden serving board",
    "cool pale stone",
    "restrained overhead",
    "reject",
    "The bright brass vessel and wooden board do not match the approved charcoal-kadhai setup; the item is also unmapped.",
    kadhaiReshoot,
  ),
  "food-papdi-chaat": reviewed(
    "ivory-coupe",
    "pale green plate on a gold charger",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The gold charger, green plate, and exposed wood are all noncompliant with ivory-coupe.",
    ivoryReshoot,
  ),
  "food-punjabi-samosa": reviewed(
    "ivory-coupe",
    "white round coupe plate",
    "warm limestone",
    "35–45-degree",
    "pass",
    "The white round plate and neutral background match the ivory-coupe system.",
    "Retain the reviewed source and crop.",
  ),
  "food-raw-mango-salad": reviewed(
    "ivory-coupe",
    "white oval fine-dining plate",
    "charcoal surface",
    "35–45-degree",
    "temporary",
    "The plate color is acceptable, but the oval plate and dark background break the required category system.",
    ivoryReshoot,
  ),
  "food-samosa-chaat": reviewed(
    "ivory-coupe",
    "pale green plate on a gold charger",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "The gold charger, green plate, and exposed wood are all noncompliant with ivory-coupe.",
    ivoryReshoot,
  ),
  "food-tandoori-roti": reviewed(
    "bread-basket",
    "bread on floral paper without a basket",
    "white studio surface",
    "restrained overhead",
    "reject",
    "The source does not use the required natural basket or black-and-cream liner.",
    basketReshoot,
  ),
  "food-dal-makhani": reviewed(
    "charcoal-kadhai",
    "antique brass kadhai",
    "warm limestone",
    "35–45-degree",
    "temporary",
    "The setup is close, but the vessel is visibly bright brass rather than matte charcoal or dark pewter.",
    kadhaiReshoot,
  ),
  "food-malai-kofta": reviewed(
    "charcoal-kadhai",
    "pale gray ceramic bowl",
    "cool pale-stone linen",
    "restrained overhead",
    "reject",
    "The pale ceramic bowl is explicitly outside the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-paneer-tikka-masala": reviewed(
    "charcoal-kadhai",
    "brown ceramic bowl on matching saucer",
    "warm limestone",
    "35–45-degree",
    "temporary",
    "The neutral setup is controlled, but the ceramic bowl is not a charcoal Indian kadhai or handi.",
    kadhaiReshoot,
  ),
  "food-pindi-chole": reviewed(
    "charcoal-kadhai",
    "dark blue ceramic bowl",
    "warm limestone",
    "35–45-degree",
    "reject",
    "The bright blue bowl is explicitly excluded from the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-saag-burrata": reviewed(
    "charcoal-kadhai",
    "brass serving pan",
    "warm linen",
    "35–45-degree",
    "temporary",
    "The Indian vessel is coherent, but the full bright brass pan does not match matte charcoal or dark pewter.",
    kadhaiReshoot,
  ),
  "food-tandoori-paneer-makhani": reviewed(
    "charcoal-kadhai",
    "beige ceramic bowl and saucer",
    "cool pale stone",
    "35–45-degree",
    "reject",
    "The pale ceramic bowl is explicitly outside the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
  "food-veg-dum-biryani": reviewed(
    "charcoal-kadhai",
    "white ceramic bowls with separate ramekin",
    "exposed orange wood",
    "restrained overhead",
    "reject",
    "White bowls and exposed orange wood do not match the charcoal-kadhai system.",
    kadhaiReshoot,
  ),
};
