export type VenueMediaCategory =
  | "dining-room"
  | "seating"
  | "bar"
  | "bar-shelves"
  | "kitchen"
  | "kitchen-action"
  | "exterior-day"
  | "exterior-night"
  | "entrance"
  | "architecture"
  | "decor-detail"
  | "private-dining"
  | "event-setup";

export type VenueMediaUse =
  | "homepage-experience"
  | "homepage-gallery"
  | "homepage-bar"
  | "bar"
  | "about"
  | "gallery"
  | "visit"
  | "catering"
  | "social-share"
  | "google-business"
  | "review-only";

export type VenueMediaStatus = "approved" | "review" | "hold" | "reject";
export type PeopleApprovalStatus =
  "not-applicable" | "approved" | "unknown" | "rejected";

export type CropDefinition = {
  left: number;
  top: number;
  width: number;
  height: number;
};

export type VenueProcessingRecord = {
  sourceFilename: string;
  imageId: string;
  category: VenueMediaCategory;
  uses: VenueMediaUse[];
  rightsStatus: "approved";
  status: VenueMediaStatus;
  productionReady: boolean;
  peopleApproval: PeopleApprovalStatus;
  sensitiveInformationFound: boolean;
  sensitiveInformationNotes: string | null;
  qualityScore: 1 | 2 | 3 | 4 | 5;
  brightness: number;
  saturation: number;
  contrast: number;
  gamma: number;
  sharpenSigma: number;
  focalPoint: { x: number; y: number };
  heroCrop?: CropDefinition;
  landscapeCrop?: CropDefinition;
  portraitCrop?: CropDefinition;
  squareCrop?: CropDefinition;
  alt: string;
  reviewNotes: string;
  visualAudit: {
    sharpness: "strong" | "adequate" | "soft";
    exposure: string;
    whiteBalance: string;
    shadowDetail: string;
    highlightClipping: string;
    colorCast: string;
    perspective: string;
    visualClutter: string;
    peoplePresent: boolean;
    websiteSuitability: string;
    recommendedCrops: string;
    reshootRecommendation: string;
  };
  augmentationCandidate: boolean;
  augmentationReason: string;
  generativeEdit: boolean;
  generativeEditScope: "bar-shelf-bottles" | null;
  ownerApprovedEdit: boolean;
  naturalOriginalId: string | null;
};

export const SAFE_VENUE_ADJUSTMENT_LIMITS = {
  brightness: { min: 0.96, max: 1.08 },
  saturation: { min: 0.94, max: 1.08 },
  contrast: { min: 0.98, max: 1.08 },
  gamma: { min: 0.96, max: 1.04 },
  sharpenSigma: { min: 0.35, max: 0.8 },
} as const;

const common = {
  rightsStatus: "approved" as const,
  peopleApproval: "not-applicable" as const,
  sensitiveInformationFound: false,
  sensitiveInformationNotes: null,
  gamma: 1,
  generativeEdit: false,
  generativeEditScope: null,
  ownerApprovedEdit: false,
  naturalOriginalId: null,
};

const audit = (
  perspective: string,
  clutter: string,
  suitability: string,
  reshoot = "Not required for this composition.",
) => ({
  sharpness: "strong" as const,
  exposure: "Bright daylight exposure with recoverable window highlights.",
  whiteBalance: "Warm-neutral interior balance; whites remain recognizable.",
  shadowDetail: "Open shadows with usable detail.",
  highlightClipping: "Minor practical-light or window clipping only.",
  colorCast: "Mild warm cast from interior fixtures.",
  perspective,
  visualClutter: clutter,
  peoplePresent: false,
  websiteSuitability: suitability,
  recommendedCrops:
    "Use the recorded focal point; preserve primary architecture and signage.",
  reshootRecommendation: reshoot,
});

export const venueProcessingConfig: VenueProcessingRecord[] = [
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29 (1).jpeg",
    imageId: "venue-dining-wide-01",
    category: "dining-room",
    uses: ["gallery", "review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.98,
    saturation: 0.96,
    contrast: 0.99,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.53, y: 0.55 },
    alt: "Wide view of the Namak dining room with green seating and the bar beyond.",
    reviewNotes:
      "Very wide perspective and host-stand materials dominate the foreground.",
    visualAudit: audit(
      "Noticeable ultra-wide stretch at the edges.",
      "Host stand and menus in foreground.",
      "Review-only; a tighter truthful crop may work.",
      "Reshoot from a slightly narrower focal length.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29 (2).jpeg",
    imageId: "venue-dining-wide-02",
    category: "dining-room",
    uses: ["gallery", "about"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.52, y: 0.55 },
    alt: "Dining room at Namak with green chairs, set tables, pendant lighting, and the bar beyond.",
    reviewNotes:
      "Strong establishing view after restrained crop away from the host stand.",
    visualAudit: audit(
      "Moderate wide-angle perspective, acceptable centrally.",
      "Small host-stand edge at lower right.",
      "Approved for Gallery and About.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29 (3).jpeg",
    imageId: "venue-dining-portrait-01",
    category: "dining-room",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.99,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.55 },
    alt: "Portrait view across the Namak dining room toward the bar.",
    reviewNotes: "Narrow portrait framing offers less useful editorial space.",
    visualAudit: audit(
      "Vertical framing with mild edge stretch.",
      "Host stand at the lower edge.",
      "Review-only alternate.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29 (4).jpeg",
    imageId: "venue-architecture-01",
    category: "architecture",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 3,
    brightness: 1.01,
    saturation: 0.96,
    contrast: 1.01,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.55, y: 0.5 },
    alt: "Architectural view through the Namak dining room with booth seating and pendant lights.",
    reviewNotes: "Useful vertical architectural detail; crop the service edge.",
    visualAudit: audit(
      "Minor converging verticals.",
      "Service ledge at lower left.",
      "Approved as a supporting Gallery detail.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29 (5).jpeg",
    imageId: "venue-entrance-interior-01",
    category: "entrance",
    uses: ["gallery", "visit"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1.01,
    saturation: 0.96,
    contrast: 1.01,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.58, y: 0.46 },
    alt: "Interior view of the Namak entrance beside a curved booth and set table.",
    reviewNotes: "Recognizable entrance with warm seating context.",
    visualAudit: audit(
      "Mild vertical convergence.",
      "No material clutter.",
      "Approved for Visit and Gallery.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.29.jpeg",
    imageId: "venue-dining-wide-03",
    category: "dining-room",
    uses: [
      "homepage-experience",
      "homepage-gallery",
      "about",
      "gallery",
      "social-share",
    ],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 0.99,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.53, y: 0.55 },
    alt: "Dining room at Namak with green seating, warm pendant lights, and the bar in the background.",
    reviewNotes:
      "Primary homepage Experience image; crop minimizes host-stand foreground.",
    visualAudit: audit(
      "Wide but balanced architectural view.",
      "Small host stand in foreground, handled by crop.",
      "Primary approved homepage and About image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (1).jpeg",
    imageId: "venue-bar-service-01",
    category: "bar",
    uses: ["review-only"],
    status: "hold",
    productionReady: false,
    sensitiveInformationFound: true,
    sensitiveInformationNotes:
      "Operational bar work area and screens require owner review before use.",
    qualityScore: 2,
    brightness: 0.99,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.48, y: 0.5 },
    alt: "Behind-the-bar work area at Namak.",
    reviewNotes: "Hold: operational screens and service equipment are visible.",
    visualAudit: audit(
      "Mild vertical convergence.",
      "Operational equipment dominates.",
      "Hold from public website.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Composition, not shelf fullness, is the concern.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (10).jpeg",
    imageId: "venue-entrance-exterior-01",
    category: "entrance",
    uses: ["homepage-gallery", "gallery", "visit", "google-business"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.53, y: 0.45 },
    alt: "Namak Indian Restaurant & Bar entrance and signage on Greenville Avenue in Dallas.",
    reviewNotes:
      "Clear signage and entrance; portrait framing suits Visit supporting media.",
    visualAudit: audit(
      "Straightforward storefront perspective.",
      "No significant obstruction.",
      "Approved for Visit, Gallery, and Google Business export.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (11).jpeg",
    imageId: "venue-entrance-exterior-02",
    category: "entrance",
    uses: ["gallery", "visit", "google-business"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.51, y: 0.48 },
    alt: "Front entrance and Namak signage viewed from the Greenville Avenue parking area.",
    reviewNotes: "Clear alternate entrance framing.",
    visualAudit: audit(
      "Minor handheld tilt corrected by crop.",
      "No private plate details are legible.",
      "Approved supporting exterior image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (2).jpeg",
    imageId: "venue-bar-wide-01",
    category: "bar",
    uses: ["homepage-bar", "gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.55 },
    alt: "Bar at Namak with green counter seating, warm wood shelving, and a white stone counter.",
    reviewNotes:
      "Primary real-bar replacement for homepage stock; keep television secondary in crop.",
    visualAudit: audit(
      "Strong symmetrical frontal perspective.",
      "Television content is present but secondary.",
      "Approved actual Namak bar image.",
    ),
    augmentationCandidate: false,
    augmentationReason:
      "Natural shelf spacing is balanced; no alteration needed.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (3).jpeg",
    imageId: "venue-bar-wide-02",
    category: "bar",
    uses: ["bar", "gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.53 },
    alt: "Full Namak bar with back shelving, draft taps, glassware, and a pale stone counter.",
    reviewNotes: "Strong real-bar hero option; no shelf augmentation needed.",
    visualAudit: audit(
      "Straight frontal perspective.",
      "Television content and a menu binder are visible.",
      "Approved for Bar and Gallery.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Existing inventory and negative space look natural.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (4).jpeg",
    imageId: "venue-bar-shelves-01-natural",
    category: "bar-shelves",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.52, y: 0.45 },
    alt: "Natural bottle shelving at one end of the Namak bar.",
    reviewNotes:
      "Crop can improve composition; augmentation is not recommended.",
    visualAudit: audit(
      "Vertical detail with mild convergence.",
      "Counter equipment at lower edge.",
      "Review-only shelf detail.",
    ),
    augmentationCandidate: true,
    augmentationReason:
      "Some upper cubbies are open, but a truthful crop solves the balance better than editing.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (5).jpeg",
    imageId: "venue-bar-shelves-02-natural",
    category: "bar-shelves",
    uses: ["review-only"],
    status: "hold",
    productionReady: false,
    sensitiveInformationFound: true,
    sensitiveInformationNotes:
      "POS display is visible in the working bar area.",
    qualityScore: 2,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.45 },
    alt: "Bottle shelving and service station at the Namak bar.",
    reviewNotes: "Hold because an operational POS screen is visible.",
    visualAudit: audit(
      "Vertical detail with mild convergence.",
      "POS and service equipment dominate lower frame.",
      "Hold from public use.",
    ),
    augmentationCandidate: false,
    augmentationReason:
      "Privacy and composition issues are not solved by adding bottles.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (6).jpeg",
    imageId: "venue-bar-service-02",
    category: "bar",
    uses: ["review-only"],
    status: "hold",
    productionReady: false,
    sensitiveInformationFound: true,
    sensitiveInformationNotes:
      "Multiple operational displays are visible behind the bar.",
    qualityScore: 2,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.55, y: 0.48 },
    alt: "Behind-the-bar service aisle at Namak.",
    reviewNotes:
      "Hold from public use because operational screens are visible.",
    visualAudit: audit(
      "Long aisle perspective.",
      "POS displays and equipment are prominent.",
      "Hold from public website.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not an empty-shelf problem.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (7).jpeg",
    imageId: "venue-seating-01",
    category: "seating",
    uses: ["homepage-gallery", "gallery", "about"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1,
    saturation: 0.96,
    contrast: 1.01,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.58, y: 0.6 },
    alt: "Curved upholstered booth and set dining table near the Namak entrance.",
    reviewNotes: "Strong portrait seating detail with natural daylight.",
    visualAudit: audit(
      "Minor vertical convergence.",
      "No significant clutter.",
      "Approved for Gallery and About.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (8).jpeg",
    imageId: "venue-dining-wide-04",
    category: "dining-room",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.56 },
    alt: "Namak dining room set for service with green seating and warm pendant lights.",
    reviewNotes: "Balanced alternate dining angle.",
    visualAudit: audit(
      "Moderate wide-angle perspective.",
      "No significant clutter.",
      "Approved Gallery alternate.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30 (9).jpeg",
    imageId: "venue-dining-wide-05",
    category: "dining-room",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.57 },
    alt: "Open dining area at Namak with set tables, green chairs, and arched wall details.",
    reviewNotes: "Useful restaurant-wide Gallery frame.",
    visualAudit: audit(
      "Wide but controlled perspective.",
      "No significant clutter.",
      "Approved Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.30.jpeg",
    imageId: "venue-dining-service-01",
    category: "dining-room",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.58, y: 0.56 },
    alt: "Dining room view across the service station at Namak.",
    reviewNotes:
      "Service counter and floor mats distract from the dining-room composition.",
    visualAudit: audit(
      "Moderate wide perspective.",
      "Service station and mats are prominent.",
      "Review-only.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (1).jpeg",
    imageId: "venue-dining-bar-01",
    category: "dining-room",
    uses: ["homepage-gallery", "gallery", "about"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 0.99,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.52, y: 0.56 },
    alt: "Dining room at Namak facing the bar, with green chairs and warm pendant lighting.",
    reviewNotes: "Strong balanced venue overview.",
    visualAudit: audit(
      "Controlled wide perspective.",
      "Television content remains secondary.",
      "Approved for Gallery and About.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Natural bar shelves need no editing.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (10).jpeg",
    imageId: "venue-architecture-02",
    category: "architecture",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.52, y: 0.54 },
    alt: "Namak dining room architecture with arched wall panels and pendant lights.",
    reviewNotes: "Vertical architectural detail for Gallery variety.",
    visualAudit: audit(
      "Mild vertical convergence.",
      "No significant clutter.",
      "Approved supporting Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (2).jpeg",
    imageId: "venue-bar-service-03",
    category: "bar",
    uses: ["review-only"],
    status: "hold",
    productionReady: false,
    sensitiveInformationFound: true,
    sensitiveInformationNotes:
      "A POS interface is visible at the right side of the bar.",
    qualityScore: 3,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.45, y: 0.5 },
    alt: "Long view behind the Namak bar.",
    reviewNotes:
      "Hold unless an owner-approved crop fully removes the POS area.",
    visualAudit: audit(
      "Long diagonal bar perspective.",
      "Operational screen at right edge.",
      "Hold from public use.",
    ),
    augmentationCandidate: false,
    augmentationReason: "No shelf augmentation needed.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (3).jpeg",
    imageId: "venue-dining-window-01",
    category: "dining-room",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.51, y: 0.55 },
    alt: "Daylit Namak dining room with set tables beside the front windows.",
    reviewNotes: "Natural daylight view with slightly strong window exposure.",
    visualAudit: audit(
      "Balanced horizontal framing.",
      "Exterior vehicles are distant and plates are not legible.",
      "Approved Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (4).jpeg",
    imageId: "venue-dining-wide-06",
    category: "dining-room",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.57 },
    alt: "Wide daylit dining room at Namak with green chairs and arched wall panels.",
    reviewNotes: "Excellent alternate wide dining frame.",
    visualAudit: audit(
      "Strong, controlled room perspective.",
      "No significant clutter.",
      "Approved Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (5).jpeg",
    imageId: "venue-dining-window-02",
    category: "dining-room",
    uses: ["homepage-gallery", "gallery", "about"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.99,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.58, y: 0.58 },
    alt: "Daylit Namak dining room with green seating, set tables, and pendant lights.",
    reviewNotes:
      "Strong atmosphere image; crop reduces the window and foreground counter.",
    visualAudit: audit(
      "Balanced room perspective.",
      "Exterior vehicles remain distant; bottle labels are incidental.",
      "Approved for Gallery and About.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a shelf edit candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (6).jpeg",
    imageId: "venue-bar-wide-03",
    category: "bar",
    uses: ["gallery", "bar"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.46, y: 0.55 },
    alt: "Namak bar shelving, draft taps, glassware, and stainless service counter.",
    reviewNotes: "Approved with a crop that excludes the far-right work area.",
    visualAudit: audit(
      "Strong diagonal bar perspective.",
      "Television content is visible; far-right operational area should be cropped.",
      "Approved supporting Bar/Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Shelves are naturally stocked and balanced.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (7).jpeg",
    imageId: "venue-bar-detail-01",
    category: "bar",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.43, y: 0.63 },
    alt: "Wine bottles and floral arrangement on the Namak bar counter.",
    reviewNotes:
      "Branded bottles and television imagery dominate; retain for owner review only.",
    visualAudit: audit(
      "Portrait bar detail.",
      "Large floral arrangement, brand labels, and TV content compete.",
      "Review-only.",
    ),
    augmentationCandidate: false,
    augmentationReason: "No empty-shelf concern.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (8).jpeg",
    imageId: "venue-seating-02",
    category: "seating",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.56, y: 0.6 },
    alt: "Set tables and green dining chairs near the front windows at Namak.",
    reviewNotes: "Inviting seating detail for Gallery.",
    visualAudit: audit(
      "Natural horizontal perspective.",
      "Exterior parking is visible but secondary.",
      "Approved Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31 (9).jpeg",
    imageId: "venue-seating-03",
    category: "seating",
    uses: ["gallery"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.62 },
    alt: "Curved booth and green chairs around a set table in the Namak dining room.",
    reviewNotes: "Strong vertical seating detail.",
    visualAudit: audit(
      "Mild vertical convergence.",
      "No significant clutter.",
      "Approved Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.31.jpeg",
    imageId: "venue-dining-wide-07",
    category: "dining-room",
    uses: ["homepage-gallery", "gallery", "about"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 0.99,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.56 },
    alt: "Wide Namak dining room with set tables, green seating, arched panels, and the bar beyond.",
    reviewNotes: "One of the strongest clean dining views.",
    visualAudit: audit(
      "Strong balanced wide perspective.",
      "Small menu binders at lower edge can be cropped.",
      "Approved for homepage preview, Gallery, and About.",
    ),
    augmentationCandidate: false,
    augmentationReason: "No shelf edit needed.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (1).jpeg",
    imageId: "venue-bar-wide-04",
    category: "bar",
    uses: ["gallery", "bar"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.56 },
    alt: "Long white counter and bottle shelving inside the Namak bar.",
    reviewNotes: "Useful vertical bar perspective.",
    visualAudit: audit(
      "Mild vertical convergence.",
      "Television content is present but secondary.",
      "Approved supporting bar image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Natural shelf arrangement is sufficient.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (10).jpeg",
    imageId: "venue-kitchen-wide-01",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.52, y: 0.52 },
    alt: "Wide view down the Namak kitchen cook line and preparation counters.",
    reviewNotes:
      "Review-only: operational containers, hoses, and floor equipment are visible.",
    visualAudit: audit(
      "Long kitchen perspective.",
      "Operational floor equipment and containers are visible.",
      "Review-only; do not digitally clean.",
      "Reshoot after physical staging with a clear craft subject.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (11).jpeg",
    imageId: "venue-kitchen-wide-02",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.52 },
    alt: "Namak kitchen line with stainless equipment and preparation counters.",
    reviewNotes: "Review-only alternate; no action or plated focal point.",
    visualAudit: audit(
      "Long kitchen perspective.",
      "Operational equipment is visible without a clear subject.",
      "Review-only.",
      "Reshoot with approved chef hands plating or tandoor action.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (2).jpeg",
    imageId: "venue-bar-wide-05",
    category: "bar",
    uses: ["gallery", "bar"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.95,
    contrast: 1,
    sharpenSigma: 0.42,
    focalPoint: { x: 0.5, y: 0.55 },
    alt: "Front view of the Namak bar with draft taps, bottle shelving, and a pale counter.",
    reviewNotes: "Higher-resolution bar view; television remains secondary.",
    visualAudit: audit(
      "Strong frontal perspective.",
      "Television content is visible.",
      "Approved Bar and Gallery image.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Shelf stock and negative space are believable.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (3).jpeg",
    imageId: "venue-exterior-day-01",
    category: "exterior-day",
    uses: ["gallery", "visit", "google-business", "social-share"],
    status: "approved",
    productionReady: true,
    qualityScore: 4,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 0.99,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.55, y: 0.47 },
    alt: "Daytime exterior of Namak Indian Restaurant & Bar on Greenville Avenue in Dallas.",
    reviewNotes:
      "Clear storefront; construction lift at far right should be excluded by crop.",
    visualAudit: audit(
      "Straight storefront framing.",
      "Construction lift at far right edge.",
      "Approved with a truthful crop that preserves signage and entrance.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (4).jpeg",
    imageId: "venue-exterior-day-02",
    category: "exterior-day",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 0.99,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.48 },
    alt: "Wide daytime storefront view of Namak on Greenville Avenue.",
    reviewNotes:
      "Construction equipment and neighboring storefront reduce suitability.",
    visualAudit: audit(
      "Wide storefront perspective.",
      "Construction lift and neighboring frontage are prominent.",
      "Review-only.",
      "Reshoot after construction equipment is removed.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (5).jpeg",
    imageId: "venue-exterior-day-03",
    category: "exterior-day",
    uses: ["homepage-gallery", "gallery", "visit", "google-business"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 0.99,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.47 },
    alt: "Namak storefront and entrance beneath a clear blue Dallas sky.",
    reviewNotes:
      "Primary Visit exterior; crop excludes the lift at the extreme right.",
    visualAudit: audit(
      "Strong frontal storefront framing.",
      "Small construction lift at extreme right edge, removable through crop.",
      "Primary approved Visit exterior.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (6).jpeg",
    imageId: "venue-exterior-day-04",
    category: "exterior-day",
    uses: ["gallery", "visit", "google-business"],
    status: "approved",
    productionReady: true,
    qualityScore: 5,
    brightness: 0.98,
    saturation: 0.94,
    contrast: 0.99,
    sharpenSigma: 0.4,
    focalPoint: { x: 0.5, y: 0.47 },
    alt: "Full daytime exterior of Namak Indian Restaurant & Bar in Dallas.",
    reviewNotes:
      "Cleanest full storefront alternate with no legible private plates.",
    visualAudit: audit(
      "Straight, balanced storefront framing.",
      "No significant obstruction.",
      "Approved for Visit, Gallery, and Google Business export.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Not a bar-shelf candidate.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (7).jpeg",
    imageId: "venue-kitchen-wide-03",
    category: "kitchen",
    uses: ["review-only"],
    status: "reject",
    productionReady: false,
    qualityScore: 2,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.52 },
    alt: "Operational kitchen line at Namak.",
    reviewNotes:
      "Reject from public use: cleaning/utility items and operational clutter are visible.",
    visualAudit: audit(
      "Long kitchen perspective.",
      "Utility bottles, hoses, and bins are visible.",
      "Reject from public website; do not digitally clean.",
      "Physically stage and reshoot the kitchen.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (8).jpeg",
    imageId: "venue-kitchen-wide-04",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.58, y: 0.5 },
    alt: "Stainless Namak kitchen line and preparation pass.",
    reviewNotes:
      "Review-only: open prep containers and operational displays are visible.",
    visualAudit: audit(
      "Strong horizontal kitchen perspective.",
      "Open prep pans and screens are present.",
      "Review-only; not selected publicly.",
      "Reshoot with controlled plating action and cleared confidential displays.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32 (9).jpeg",
    imageId: "venue-kitchen-wide-05",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.5, y: 0.52 },
    alt: "Portrait view down the Namak kitchen line.",
    reviewNotes:
      "Review-only vertical alternate without a clear craft subject.",
    visualAudit: audit(
      "Vertical long-line perspective.",
      "Operational equipment is visible without a focal action.",
      "Review-only.",
      "Reshoot a specific approved craft moment.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.32.jpeg",
    imageId: "venue-architecture-03",
    category: "architecture",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.52, y: 0.52 },
    alt: "Vertical view between the Namak dining room and bar seating.",
    reviewNotes:
      "Narrow aisle composition is less useful than approved alternatives.",
    visualAudit: audit(
      "Vertical framing with mild convergence.",
      "Aisle and bar seating compress the composition.",
      "Review-only alternate.",
    ),
    augmentationCandidate: false,
    augmentationReason: "No empty-shelf concern.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.33 (1).jpeg",
    imageId: "venue-kitchen-cookline-01",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.58, y: 0.56 },
    alt: "Cook line and pans beneath the stainless hood in the Namak kitchen.",
    reviewNotes:
      "Review-only: open cookware and no active, approved craft subject.",
    visualAudit: audit(
      "Strong horizontal equipment view.",
      "Open cookware and operational line are visible.",
      "Review-only; do not imply a staged craft moment.",
      "Reshoot during controlled cooking action with approval.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
  {
    ...common,
    sourceFilename: "WhatsApp Image 2026-08-11 at 12.16.33.jpeg",
    imageId: "venue-kitchen-cookline-02",
    category: "kitchen",
    uses: ["review-only"],
    status: "review",
    productionReady: false,
    qualityScore: 3,
    brightness: 1,
    saturation: 0.96,
    contrast: 1,
    sharpenSigma: 0.38,
    focalPoint: { x: 0.52, y: 0.56 },
    alt: "Portrait view of the stainless cook line in the Namak kitchen.",
    reviewNotes:
      "Review-only; portrait crop lacks a clear approved action subject.",
    visualAudit: audit(
      "Vertical equipment view.",
      "Operational cookware and prep edge are visible.",
      "Review-only.",
      "Reshoot a controlled action or plating scene.",
    ),
    augmentationCandidate: false,
    augmentationReason: "Generative editing is prohibited for kitchen media.",
  },
];

if (
  venueProcessingConfig.some(
    (record) => record.productionReady !== (record.status === "approved"),
  )
) {
  throw new Error("Venue productionReady must match approved status.");
}
